/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip Tip With this API, you can build custom applications and integrate with third-party systems, feeds, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are required:   - `API Key`   - `Basic Auth` #### Basic Auth Basic `<credentials>`, where `<credentials>` is the Base64 encoding of user and password joined by a single colon `:` see [Wikipedia](https://en.wikipedia.org/wiki/Basic_access_authentication) on this subject.  #### API Key  An x-apikey header needs to be added to the request with the user api key from Geins Merchant Center.  #### Example ```bash curl -X GET \"https://mgmtapi.geins.io/Market/List\" \\ -H \"Authorization: Basic [USER-CREDENTIALS-BASE64-ENCODED]\" \\ -H \"X-ApiKey: [SECRET-API-KEY] ``` 
 *
 * The version of the OpenAPI document: v1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Data carrier for an order row
 * @export
 * @interface OrderModelsOrderRow
 */
export interface OrderModelsOrderRow {
    /**
     * The unique identifier for this order row
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    id?: number;
    /**
     * Product ID
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    productId?: number;
    /**
     * Order row name
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    name?: string;
    /**
     * Product name
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    productName?: string;
    /**
     * Item ID (SKU).
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    itemId?: number;
    /**
     * Item name
     * <para>E.g. XL</para>
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    itemName?: string;
    /**
     * Article number. This could be the same as ItemId or a unique value set manually.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    articleNumber?: string;
    /**
     * Order row total (affected by quantity)
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    total?: number;
    /**
     * Expected total price inc vat, inc row discount.
     * <para>The value is usually taken directly from the payment provider and represents the actual paid amount.</para><para>If this differs from Total, actions should be taken to ensure they match. This usually happens due to rounding.</para>
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    expectedTotalPriceIncVat?: number;
    /**
     * Order row discount rate
     * <para>E.g. 10% = 10.0</para>
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    discountRate?: number;
    /**
     * Order row discount sum inc VAT
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    discount?: number;
    /**
     * Expected total discount inc vat.
     * <para>The value is usually taken directly from the payment provider and represents the actual applied discount amount.</para><para>If this differs from Discount multiplied by Quantity, actions should be taken to ensure they match. This usually happens due to rounding.</para>
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    expectedTotalDiscountIncVat?: number;
    /**
     * Order row total VAT (affected by quantity)
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    vATTotal?: number;
    /**
     * VAT rate. Example: 0.25
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    vATRate?: number;
    /**
     * Quantity
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    quantity?: number;
    /**
     * Purchase price of the product
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    purchasePrice?: number;
    /**
     * A reference to the payment detail that this row belongs to
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    paymentDetailId?: number;
    /**
     * A reference to the shipping detail that this row belongs to
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    shippingDetailId?: number;
    /**
     * The market that the order row belongs to
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    market?: string;
    /**
     * Order row unit price inc vat, inc row discount
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    unitPrice?: number;
    /**
     * A reference to the product container build the row belongs to.
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    productContainerBuildId?: number;
    /**
     * A system message for this row.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    message?: string;
    /**
     * The unique identifier for the cart row from which this order row originates.
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    cartRowId?: number;
    /**
     * The identifier for the external row from which this order row originates.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    externalId?: string;
    /**
     * The identifier for a Product container selection id that is part of the product configurator module
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    productContainerSelectionId?: number;
    /**
     * The name of the product container.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    productContainerName?: string;
    /**
     * External Id of the product.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    externalProductId?: string;
    /**
     * External Id of the product item.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    externalProductItemId?: string;
    /**
     * Parcel group id for a shipped order row.
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    parcelGroupId?: number;
    /**
     * Brand name of the product.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    brandName?: string;
    /**
     * The GTIN number for the product item.
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    gtin?: string;
    /**
     * The weight of the product item in grams (g).
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    weight?: number;
    /**
     * The length of the product item in millimeters (mm).
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    length?: number;
    /**
     * The width of the product item in millimeters (mm).
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    width?: number;
    /**
     * The height of the product item in millimeters (mm).
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    height?: number;
    /**
     * Product color
     * <para>E.g. Black</para>
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    color?: string;
    /**
     * Product variant
     * <para>E.g. Black XL</para>
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    variant?: string;
    /**
     * The ids for the campaigns applied to this row
     * @type {Array<string>}
     * @memberof OrderModelsOrderRow
     */
    campaignIds?: Array<string>;
    /**
     * Contains json data describing the different campaign groups belonging to this row. 
     * Fields: i -&gt; Campaign Number (int), n -&gt; Number of items belonging to this group
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    campaignGroupData?: string;
    /**
     * Contains the the ID of the campaign group this row belongs to
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    campaignGroupId?: number;
    /**
     * The names for the campaigns applied to this row
     * @type {Array<string>}
     * @memberof OrderModelsOrderRow
     */
    campaignNames?: Array<string>;
    /**
     * The product category for the product on this order row
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    categoryId?: number;
    /**
     * GUID that connects orderrows that are part of a build
     * @type {string}
     * @memberof OrderModelsOrderRow
     */
    relatedProductsBuildId?: string;
    /**
     * The packing location of this order row
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    packingLocationId?: number;
    /**
     * The id of the applied product price campaign
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    productPriceCampaignId?: number;
    /**
     * The id of the applied product price list
     * @type {number}
     * @memberof OrderModelsOrderRow
     */
    productPriceListId?: number;
}

/**
 * Check if a given object implements the OrderModelsOrderRow interface.
 */
export function instanceOfOrderModelsOrderRow(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderModelsOrderRowFromJSON(json: any): OrderModelsOrderRow {
    return OrderModelsOrderRowFromJSONTyped(json, false);
}

export function OrderModelsOrderRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderModelsOrderRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'productId': !exists(json, 'ProductId') ? undefined : json['ProductId'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'productName': !exists(json, 'ProductName') ? undefined : json['ProductName'],
        'itemId': !exists(json, 'ItemId') ? undefined : json['ItemId'],
        'itemName': !exists(json, 'ItemName') ? undefined : json['ItemName'],
        'articleNumber': !exists(json, 'ArticleNumber') ? undefined : json['ArticleNumber'],
        'total': !exists(json, 'Total') ? undefined : json['Total'],
        'expectedTotalPriceIncVat': !exists(json, 'ExpectedTotalPriceIncVat') ? undefined : json['ExpectedTotalPriceIncVat'],
        'discountRate': !exists(json, 'DiscountRate') ? undefined : json['DiscountRate'],
        'discount': !exists(json, 'Discount') ? undefined : json['Discount'],
        'expectedTotalDiscountIncVat': !exists(json, 'ExpectedTotalDiscountIncVat') ? undefined : json['ExpectedTotalDiscountIncVat'],
        'vATTotal': !exists(json, 'VATTotal') ? undefined : json['VATTotal'],
        'vATRate': !exists(json, 'VATRate') ? undefined : json['VATRate'],
        'quantity': !exists(json, 'Quantity') ? undefined : json['Quantity'],
        'purchasePrice': !exists(json, 'PurchasePrice') ? undefined : json['PurchasePrice'],
        'paymentDetailId': !exists(json, 'PaymentDetailId') ? undefined : json['PaymentDetailId'],
        'shippingDetailId': !exists(json, 'ShippingDetailId') ? undefined : json['ShippingDetailId'],
        'market': !exists(json, 'Market') ? undefined : json['Market'],
        'unitPrice': !exists(json, 'UnitPrice') ? undefined : json['UnitPrice'],
        'productContainerBuildId': !exists(json, 'ProductContainerBuildId') ? undefined : json['ProductContainerBuildId'],
        'message': !exists(json, 'Message') ? undefined : json['Message'],
        'cartRowId': !exists(json, 'CartRowId') ? undefined : json['CartRowId'],
        'externalId': !exists(json, 'ExternalId') ? undefined : json['ExternalId'],
        'productContainerSelectionId': !exists(json, 'ProductContainerSelectionId') ? undefined : json['ProductContainerSelectionId'],
        'productContainerName': !exists(json, 'ProductContainerName') ? undefined : json['ProductContainerName'],
        'externalProductId': !exists(json, 'ExternalProductId') ? undefined : json['ExternalProductId'],
        'externalProductItemId': !exists(json, 'ExternalProductItemId') ? undefined : json['ExternalProductItemId'],
        'parcelGroupId': !exists(json, 'ParcelGroupId') ? undefined : json['ParcelGroupId'],
        'brandName': !exists(json, 'BrandName') ? undefined : json['BrandName'],
        'gtin': !exists(json, 'Gtin') ? undefined : json['Gtin'],
        'weight': !exists(json, 'Weight') ? undefined : json['Weight'],
        'length': !exists(json, 'Length') ? undefined : json['Length'],
        'width': !exists(json, 'Width') ? undefined : json['Width'],
        'height': !exists(json, 'Height') ? undefined : json['Height'],
        'color': !exists(json, 'Color') ? undefined : json['Color'],
        'variant': !exists(json, 'Variant') ? undefined : json['Variant'],
        'campaignIds': !exists(json, 'CampaignIds') ? undefined : json['CampaignIds'],
        'campaignGroupData': !exists(json, 'CampaignGroupData') ? undefined : json['CampaignGroupData'],
        'campaignGroupId': !exists(json, 'CampaignGroupId') ? undefined : json['CampaignGroupId'],
        'campaignNames': !exists(json, 'CampaignNames') ? undefined : json['CampaignNames'],
        'categoryId': !exists(json, 'CategoryId') ? undefined : json['CategoryId'],
        'relatedProductsBuildId': !exists(json, 'RelatedProductsBuildId') ? undefined : json['RelatedProductsBuildId'],
        'packingLocationId': !exists(json, 'PackingLocationId') ? undefined : json['PackingLocationId'],
        'productPriceCampaignId': !exists(json, 'ProductPriceCampaignId') ? undefined : json['ProductPriceCampaignId'],
        'productPriceListId': !exists(json, 'ProductPriceListId') ? undefined : json['ProductPriceListId'],
    };
}

export function OrderModelsOrderRowToJSON(value?: OrderModelsOrderRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'ProductId': value.productId,
        'Name': value.name,
        'ProductName': value.productName,
        'ItemId': value.itemId,
        'ItemName': value.itemName,
        'ArticleNumber': value.articleNumber,
        'Total': value.total,
        'ExpectedTotalPriceIncVat': value.expectedTotalPriceIncVat,
        'DiscountRate': value.discountRate,
        'Discount': value.discount,
        'ExpectedTotalDiscountIncVat': value.expectedTotalDiscountIncVat,
        'VATTotal': value.vATTotal,
        'VATRate': value.vATRate,
        'Quantity': value.quantity,
        'PurchasePrice': value.purchasePrice,
        'PaymentDetailId': value.paymentDetailId,
        'ShippingDetailId': value.shippingDetailId,
        'Market': value.market,
        'UnitPrice': value.unitPrice,
        'ProductContainerBuildId': value.productContainerBuildId,
        'Message': value.message,
        'CartRowId': value.cartRowId,
        'ExternalId': value.externalId,
        'ProductContainerSelectionId': value.productContainerSelectionId,
        'ProductContainerName': value.productContainerName,
        'ExternalProductId': value.externalProductId,
        'ExternalProductItemId': value.externalProductItemId,
        'ParcelGroupId': value.parcelGroupId,
        'BrandName': value.brandName,
        'Gtin': value.gtin,
        'Weight': value.weight,
        'Length': value.length,
        'Width': value.width,
        'Height': value.height,
        'Color': value.color,
        'Variant': value.variant,
        'CampaignIds': value.campaignIds,
        'CampaignGroupData': value.campaignGroupData,
        'CampaignGroupId': value.campaignGroupId,
        'CampaignNames': value.campaignNames,
        'CategoryId': value.categoryId,
        'RelatedProductsBuildId': value.relatedProductsBuildId,
        'PackingLocationId': value.packingLocationId,
        'ProductPriceCampaignId': value.productPriceCampaignId,
        'ProductPriceListId': value.productPriceListId,
    };
}

